#!/usr/bin/env bash
# Creates the Entra ID objects for CDF auth and writes a .env into a project folder.
#
#   cdf-auth-setup.sh --tenant <guid> --cluster <cluster> --cdf-project <name> \
#                     [--prefix cdf] [--root <dir>] [--days 180] [--force] [--plan-only]
#
# Terraform state is kept per-project in <root>/.cdf-auth/, so several projects can
# each own their own credentials without fighting over one state file.

set -uo pipefail

MODULE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

TENANT="" CLUSTER="" CDF_PROJECT="" PREFIX="cdf" ROOT="" DAYS="180"
FORCE=0 PLAN_ONLY=0

die() { printf '\033[31merror:\033[0m %s\n' "$1" >&2; exit 1; }
info() { printf '\033[1m%s\033[0m\n' "$1"; }

while [[ $# -gt 0 ]]; do
  case "$1" in
    --tenant)      TENANT="${2:-}"; shift 2 ;;
    --cluster)     CLUSTER="${2:-}"; shift 2 ;;
    --cdf-project) CDF_PROJECT="${2:-}"; shift 2 ;;
    --prefix)      PREFIX="${2:-}"; shift 2 ;;
    --root)        ROOT="${2:-}"; shift 2 ;;
    --days)        DAYS="${2:-}"; shift 2 ;;
    --force)       FORCE=1; shift ;;
    --plan-only)   PLAN_ONLY=1; shift ;;
    *) die "unknown argument: $1" ;;
  esac
done

command -v terraform >/dev/null 2>&1 || die "terraform not found on PATH"
command -v az >/dev/null 2>&1        || die "az (Azure CLI) not found on PATH"

[[ -n "$TENANT" ]]      || die "--tenant is required"
[[ -n "$CLUSTER" ]]     || die "--cluster is required"
[[ -n "$CDF_PROJECT" ]] || die "--cdf-project is required"

[[ "$TENANT" =~ ^[0-9a-fA-F-]{36}$ ]] || die "--tenant must be a GUID, got: $TENANT"
[[ "$TENANT" != "00000000-0000-0000-0000-000000000000" ]] || die "--tenant is the placeholder GUID"

# --- where the .env goes -----------------------------------------------------
# Default to the git repo root of the current directory, falling back to cwd.
if [[ -z "$ROOT" ]]; then
  ROOT="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
fi
[[ -d "$ROOT" ]] || die "--root is not a directory: $ROOT"
ROOT="$(cd "$ROOT" && pwd)"

ENV_FILE="$ROOT/.env"
WORK="$ROOT/.cdf-auth"

# Never silently clobber someone's existing .env.
if [[ -e "$ENV_FILE" && "$FORCE" -eq 0 && ! -d "$WORK" ]]; then
  die "$ENV_FILE already exists and is not managed by this tool. Re-run with --force to overwrite."
fi

# --- verify the az session targets the right tenant --------------------------
ACTIVE_TENANT="$(az account show --query tenantId -o tsv 2>/dev/null)"
if [[ -z "$ACTIVE_TENANT" ]]; then
  die "not logged in to Azure. Run: az login --tenant $TENANT --allow-no-subscriptions"
fi
if [[ "$ACTIVE_TENANT" != "$TENANT" ]]; then
  die "az session is on tenant $ACTIVE_TENANT but --tenant is $TENANT.
       Creating directory objects in the wrong tenant fails with 403 Authorization_RequestDenied.
       Fix with: az login --tenant $TENANT --allow-no-subscriptions"
fi

# --- assemble a per-project terraform working directory ----------------------
info "Preparing $WORK"
mkdir -p "$WORK/templates"
for f in versions.tf providers.tf variables.tf main.tf outputs.tf verify.sh; do
  [[ -f "$MODULE_DIR/$f" ]] || die "module file missing: $MODULE_DIR/$f"
  cp "$MODULE_DIR/$f" "$WORK/$f"
done
cp "$MODULE_DIR/templates/env.tftpl" "$WORK/templates/env.tftpl"
chmod +x "$WORK/verify.sh"

cat > "$WORK/terraform.tfvars" <<EOF
# Generated by cdf-auth-setup.sh — edit and re-run to change.
tenant_id            = "$TENANT"
name_prefix          = "$PREFIX"
cdf_cluster          = "$CLUSTER"
cdf_project          = "$CDF_PROJECT"
secret_validity_days = $DAYS
env_file_path        = "$ENV_FILE"
EOF

# Keep credentials and state out of the user's git history.
IGNORE="$ROOT/.gitignore"
for pat in ".env" ".cdf-auth/"; do
  if ! grep -qxF "$pat" "$IGNORE" 2>/dev/null; then
    { [[ -s "$IGNORE" ]] && printf '\n'; printf '# added by cdf-auth-bootstrap\n%s\n' "$pat"; } >> "$IGNORE"
    echo "  added '$pat' to .gitignore"
  fi
done

# --- run terraform -----------------------------------------------------------
info "Running terraform"
terraform -chdir="$WORK" init -input=false -no-color >/dev/null || die "terraform init failed"

if [[ "$PLAN_ONLY" -eq 1 ]]; then
  terraform -chdir="$WORK" plan -input=false -no-color
  exit $?
fi

if ! terraform -chdir="$WORK" apply -auto-approve -input=false -no-color; then
  die "terraform apply failed — nothing was written to $ENV_FILE"
fi

# --- verify ------------------------------------------------------------------
info "Verifying against Microsoft Graph"
"$WORK/verify.sh"
VERIFY_RC=$?

GROUP_ID="$(terraform -chdir="$WORK" output -raw group_object_id 2>/dev/null)"
CLIENT_ID="$(terraform -chdir="$WORK" output -raw client_id 2>/dev/null)"

cat <<EOF

$(info "Done")
  .env written to   $ENV_FILE  (mode 0600)
  client id         $CLIENT_ID
  Entra group id    $GROUP_ID
  terraform state   $WORK/terraform.tfstate  (holds the secret — keep it private)

Next step in CDF: create a group with sourceId = $GROUP_ID and the capabilities you need.
To tear everything down: terraform -chdir="$WORK" destroy
EOF

exit $VERIFY_RC
